### ISSUE TITLE
Add rclone backend

### ISSUE THREAD

**Issue by tamalsaha** [stashed/project#4]
https://restic.net/blog/2018-04-01/rclone-backend

**Comment by unixfox** [comment]
Restic can now work directly with rclone without any need to use a REST API server: https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone

It's just "as simple" as specifying rclone as a repository backend for restic. The amount of changes into stash should be very minimal due to the great integration between restic and rclone.

**Comment by hossainemruz** [comment]
Thank you @unixfox for letting us know. We are currently working on Stash v1beta2 API. Once the new API is ready, we can add this feature. I have already added this in the feature queue.

**Comment by unixfox** [comment]
For anyone looking for using rclone into stash, it is possible with minor modifications. This will restrict the ability to use REST servers, though.
Basically, you just have to replace `rest:` by `rclone:` in https://github.com/stashed/stash/blob/master/vendor/stash.appscode.dev/apimachinery/pkg/restic/setup.go#L308. Then recompile the Docker image with rclone included in it.
You can then modify the default docker image using `--set stash-community.operator.registry=yourusername --set stash-community.crdInstaller.registry=stashed`.

If you don't want to rebuild a Docker image, I maintain these modifications under this Docker image: https://quay.io/repository/unixfox/stash

After that, you can configure your Repository configurations by typing the rclone remote name after `url:` like:
```yaml
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: rest-repo
  namespace: demo
spec:
  backend:
    rest:
      url: ftp:backup
    storageSecretName: rest-secret
```

Don't forget to specify how rclone will have to use this remote using the environment variables inside your BackupConfiguration like this example:
```yaml
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: ss-backup
  namespace: demo
spec:
  repository:
    name: rest-repo
  schedule: "*/5 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: stash-demo
    volumeMounts:
    - name: source-data
      mountPath: /source/data
    paths:
    - /source/data
  runtimeSettings:
    container:
      env:
        - name: RCLONE_CONFIG_FTP_TYPE
          value: "ftp"
        - name: RCLONE_CONFIG_FTP_HOST
          value: "1.1.1.1"
        - name: RCLONE_CONFIG_FTP_USER
          value: "username"
        - name: RCLONE_CONFIG_FTP_PASS
          value: "mypass"
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
```
It's not possible to do it using a rclone config as you can't mount files to a stash sidecar.
