### ISSUE TITLE
Support templating for exec hook commands

### ISSUE THREAD

**Issue by hmsayem** [stashed/project#43]
```
# option 1
  hooks:
    postBackup:
      executionPolicy: Always
      exec:
        command:
        {{- range $cmd := list "curl" "-d" (printf "{\"text\":\":x: ENV (Percona) Backup failed for %s/%s Reason: %s.\"}" .Namespace .Target.Name .Status.Error) "-x" "secret-proxy-url" "-H" "Content-Type: application/json" "-X" "POST" "https://slack-webhook.url/stash" }}
          - {{ $cmd }}
        {{- end }}
      containerName: mysql

# Invalid value: "string": spec.hooks.postBackup.exec.command in body must be of type array: "string".

# option 2
        command:
          - curl
          - -d
          - '{"text":":x: ENV (Percona) Backup failed for {{ .Namespace }}/{{ .Target.Name }} Reason: {{ .Status.Error }}."}'
          - -x
          - secret-proxy-url
          - -H
          - "Content-Type: application/json"
          - -X
          - POST
          - https://slack-webhook.url/stash

# message is sent via curl but {{ .Namespace }}/{{ .Target.Name }} Reason: {{ .Status.Error }} is hardcoded and not evaluated by Go template
```
